import {supabaseRequest as supabase} from "../../../lib/supabase-server";
import {forbidden,getStaffRole} from "../../../lib/staff-session";
type TournamentRow={id:string;name:string;status:string;data:unknown;created_at:string;updated_at:string};
type StoredGame=Record<string,unknown>&{id?:string};
type StoredData=Record<string,unknown>&{games?:StoredGame[]};
const present=(row:TournamentRow)=>({id:row.id,name:row.name,status:row.status,data:row.data,createdAt:row.created_at,updatedAt:row.updated_at});
const fail=(error:unknown)=>{console.error(error);return Response.json({error:"大会データを保存できませんでした"},{status:500})};
const resultFields=["sa","sb","ya","yb","ra","rb","pa","pb","pka","pkb","done"] as const;
const refereeData=(stored:unknown,incoming:unknown)=>{const current=stored as StoredData,next=incoming as StoredData;if(!Array.isArray(current?.games)||!Array.isArray(next?.games))return current;const submitted=new Map(next.games.map(game=>[game.id,game]));return{...current,games:current.games.map(game=>{const update=submitted.get(game.id);if(!update)return game;const result={...game};for(const field of resultFields)if(field in update)result[field]=update[field];return result})}};

export async function GET(){try{const rows=await supabase("football_tournaments?select=*&order=updated_at.desc") as TournamentRow[];return Response.json({tournaments:rows.map(present)})}catch(error){return fail(error)}}
export async function POST(request:Request){if(await getStaffRole(request)!=="admin")return forbidden();try{const body=await request.json() as {name?:string;status?:string;data?:unknown};if(!body.name)return Response.json({error:"大会名が必要です"},{status:400});const [row]=await supabase("football_tournaments",{method:"POST",body:JSON.stringify({name:body.name,status:body.status||"draft",data:body.data||{}})}) as TournamentRow[];return Response.json({tournament:present(row)},{status:201})}catch(error){return fail(error)}}
export async function PUT(request:Request){const role=await getStaffRole(request);if(!role)return forbidden();try{const body=await request.json() as {id?:string;name?:string;status?:string;data?:unknown};if(!body.id||!body.name)return Response.json({error:"保存情報が不足しています"},{status:400});let patch:Record<string,unknown>;if(role==="admin")patch={name:body.name,status:body.status||"draft",data:body.data||{},updated_at:new Date().toISOString()};else{const [current]=await supabase(`football_tournaments?id=eq.${encodeURIComponent(body.id)}&select=*`) as TournamentRow[];if(!current)return Response.json({error:"大会が見つかりません"},{status:404});patch={data:refereeData(current.data,body.data),updated_at:new Date().toISOString()}}const [row]=await supabase(`football_tournaments?id=eq.${encodeURIComponent(body.id)}`,{method:"PATCH",body:JSON.stringify(patch)}) as TournamentRow[];if(!row)return Response.json({error:"大会が見つかりません"},{status:404});return Response.json({tournament:present(row)})}catch(error){return fail(error)}}
export async function DELETE(request:Request){if(await getStaffRole(request)!=="admin")return forbidden();try{const id=new URL(request.url).searchParams.get("id");if(!id)return Response.json({error:"IDが必要です"},{status:400});await supabase(`football_tournaments?id=eq.${encodeURIComponent(id)}`,{method:"DELETE",headers:{Prefer:"return=minimal"}});return Response.json({ok:true})}catch(error){return fail(error)}}
