import {supabaseRequest as supabase} from "../../../lib/supabase-server";
type TournamentRow={id:string;name:string;status:string;data:unknown;created_at:string;updated_at:string};
const present=(row:TournamentRow)=>({id:row.id,name:row.name,status:row.status,data:row.data,createdAt:row.created_at,updatedAt:row.updated_at});
const fail=(error:unknown)=>{console.error(error);return Response.json({error:"大会データを保存できませんでした"},{status:500})};

export async function GET(){try{const rows=await supabase("football_tournaments?select=*&order=updated_at.desc") as TournamentRow[];return Response.json({tournaments:rows.map(present)})}catch(error){return fail(error)}}
export async function POST(request:Request){try{const body=await request.json() as {name?:string;status?:string;data?:unknown};if(!body.name)return Response.json({error:"大会名が必要です"},{status:400});const [row]=await supabase("football_tournaments",{method:"POST",body:JSON.stringify({name:body.name,status:body.status||"draft",data:body.data||{}})}) as TournamentRow[];return Response.json({tournament:present(row)},{status:201})}catch(error){return fail(error)}}
export async function PUT(request:Request){try{const body=await request.json() as {id?:string;name?:string;status?:string;data?:unknown};if(!body.id||!body.name)return Response.json({error:"保存情報が不足しています"},{status:400});const [row]=await supabase(`football_tournaments?id=eq.${encodeURIComponent(body.id)}`,{method:"PATCH",body:JSON.stringify({name:body.name,status:body.status||"draft",data:body.data||{},updated_at:new Date().toISOString()})}) as TournamentRow[];if(!row)return Response.json({error:"大会が見つかりません"},{status:404});return Response.json({tournament:present(row)})}catch(error){return fail(error)}}
export async function DELETE(request:Request){try{const id=new URL(request.url).searchParams.get("id");if(!id)return Response.json({error:"IDが必要です"},{status:400});await supabase(`football_tournaments?id=eq.${encodeURIComponent(id)}`,{method:"DELETE",headers:{Prefer:"return=minimal"}});return Response.json({ok:true})}catch(error){return fail(error)}}
