"use client";
import {useEffect,useState,type Dispatch,type SetStateAction} from "react";
import {AlertTriangle,Bell,CalendarDays,Check,Clock3,CloudOff,Copy,Download,FileText,Flag,KeyRound,LockKeyhole,LogOut,MapPin,Minus,Play,Plus,PlusCircle,Printer,RefreshCw,RotateCcw,Send,Settings,ShieldCheck,Smartphone,Square,Trophy,Volume2,X} from "lucide-react";

type Tab="bracket"|"schedule"|"guide"|"score"|"settings"|"system";
type Info={name:string,date:string,time:string,venue:string,address:string,map:string,host:string,fee:string,target:string,parking:string,rain:string,medical:string,notes:string,awards:string,flow:string};
const initialInfo:Info={name:"第六回 Bond Cup",date:"2026年8月8日（土）",time:"9:00〜17:15",venue:"東諸福公園",address:"大阪府大東市諸福1丁目",map:"https://maps.app.goo.gl/GAYGZYEobeV1CZP56",host:"OXALA大東・東大阪（株式会社From Earth Kids）",fee:"1チーム 7,000円",target:"U-10〜U-12（混合チーム可）",parking:"会場駐車場はありません。近隣のコインパーキングをご利用ください。路上駐車、近隣商業施設への無断駐車はご遠慮ください。",rain:"小雨決行。警報発令時やグラウンド状況が悪い場合は、前日20:00以降に判断してご連絡します。",medical:"主催者にて応急手当を行います。その後の処置は各チームでご対応ください。参加者はスポーツ保険への加入をお願いします。",notes:"開会式はありません。各チーム最初の試合に間に合うようご来場ください。\n日陰が少ないため、チームごとにテントと十分な飲料をご準備ください。\n公共の公園です。遊具やベンチは譲り合ってご利用ください。",awards:"優勝：トロフィー／2位・3位：入賞盾／チャレンジカップ優勝：敢闘賞／各チーム1名：MVP賞",flow:"8:45　受付開始\n9:10〜15:40　トーナメント\n15:40〜17:00　PK大会\n17:00〜17:10　表彰式・閉会式"};
type Game={id:string;no:string;time:string;court:string;round:string;a:string|null;b:string|null;sa:number;sb:number;pa?:number;pb?:number;done:boolean;stage:"main"|"challenge";ya:number;yb:number;ra:number;rb:number};
const seed:Game[]=[
 {id:"m1",no:"M01",time:"09:00",court:"Aコート",round:"1回戦",a:"青葉FC",b:"港南ジュニア",sa:2,sb:0,done:true,stage:"main",ya:0,yb:1,ra:0,rb:0},
 {id:"m2",no:"M02",time:"09:00",court:"Bコート",round:"1回戦",a:"城北アローズ",b:"さくらSC",sa:1,sb:1,pa:4,pb:3,done:true,stage:"main",ya:1,yb:0,ra:0,rb:0},
 {id:"m3",no:"M03",time:"09:40",court:"Aコート",round:"1回戦",a:"大空イレブン",b:"若葉ユナイテッド",sa:0,sb:0,done:false,stage:"main",ya:0,yb:0,ra:0,rb:0},
 {id:"m4",no:"M04",time:"09:40",court:"Bコート",round:"1回戦",a:"南町キッカーズ",b:"北星FC",sa:0,sb:0,done:false,stage:"main",ya:0,yb:0,ra:0,rb:0},
 {id:"m5",no:"M05",time:"10:40",court:"Aコート",round:"準決勝",a:"青葉FC",b:"城北アローズ",sa:0,sb:0,done:false,stage:"main",ya:0,yb:0,ra:0,rb:0},
 {id:"m6",no:"M06",time:"10:40",court:"Bコート",round:"準決勝",a:null,b:null,sa:0,sb:0,done:false,stage:"main",ya:0,yb:0,ra:0,rb:0},
 {id:"m7",no:"M07",time:"12:00",court:"Aコート",round:"決勝",a:null,b:null,sa:0,sb:0,done:false,stage:"main",ya:0,yb:0,ra:0,rb:0},
 {id:"c1",no:"C01",time:"10:20",court:"Cコート",round:"1回戦",a:"港南ジュニア",b:"さくらSC",sa:0,sb:0,done:false,stage:"challenge",ya:0,yb:0,ra:0,rb:0},
 {id:"c2",no:"C02",time:"11:00",court:"Cコート",round:"1回戦",a:null,b:null,sa:0,sb:0,done:false,stage:"challenge",ya:0,yb:0,ra:0,rb:0},
 {id:"c3",no:"C03",time:"12:00",court:"Cコート",round:"決勝",a:null,b:null,sa:0,sb:0,done:false,stage:"challenge",ya:0,yb:0,ra:0,rb:0},
];
const colors=["#1680d8","#ef7c35","#7b55c7","#e15292","#17a5b7","#39a763","#d5a51c","#40566d"];
function Mark({name}:{name:string|null}){let i=Math.abs((name||"").split("").reduce((n,c)=>n+c.charCodeAt(0),0))%colors.length;return <i className="mark" style={{background:colors[i]}}>{name?.[0]||"?"}</i>}
function Team({name}:{name:string|null}){return <span className={!name?"team muted":"team"}><Mark name={name}/>{name||"対戦待ち"}</span>}
function Card({g}:{g:Game}){return <div className={g.done?"game done":"game"}><small>{g.no}{g.done&&<em><Check/>終了</em>}</small><p><Team name={g.a}/><b>{g.done?g.sa:"–"}</b></p><p><Team name={g.b}/><b>{g.done?g.sb:"–"}</b></p>{g.pa!==undefined&&<footer>PK {g.pa} - {g.pb}</footer>}</div>}

export default function Home(){
 const [tab,setTab]=useState<Tab>("bracket"),[admin,setAdmin]=useState(false),[login,setLogin]=useState(false),[pin,setPin]=useState(""),[adminPassword,setAdminPassword]=useState("1234"),[games,setGames]=useState(seed),[recovery,setRecovery]=useState<Game|null>(null),[pendingResult,setPendingResult]=useState<Game|null>(null),[id,setId]=useState("m3"),[stage,setStage]=useState<"main"|"challenge">("main"),[court,setCourt]=useState("すべて"),[mins,setMins]=useState(15),[format,setFormat]=useState("half"),[pkRule,setPkRule]=useState(3),[pk,setPk]=useState(false),[secs,setSecsRaw]=useState(0),[running,setRunning]=useState(false),[phase,setPhase]=useState("試合前"),[activeHalf,setActiveHalf]=useState<"前半"|"後半">("前半"),[paused,setPaused]=useState(false),[lossFirst,setLossFirst]=useState(0),[lossSecond,setLossSecond]=useState(0),[confirm,setConfirm]=useState(false),[toast,setToast]=useState(false),[toastMessage,setToastMessage]=useState("結果を送信しました"),[info,setInfo]=useState(initialInfo),[editing,setEditing]=useState(false),[copied,setCopied]=useState(false),[published,setPublished]=useState(false),[publishConfirm,setPublishConfirm]=useState(false);
 const setSecs=(value:SetStateAction<number>)=>setSecsRaw(typeof value==="number"?0:value);
 const g=games.find(x=>x.id===id)!; const edit=(p:Partial<Game>)=>setGames(xs=>xs.map(x=>x.id===id?{...x,...p}:x)); const add=(k:keyof Game,n:number)=>edit({[k]:Math.max(0,Number(g[k]||0)+n)} as Partial<Game>);
 useEffect(()=>{if(!running)return;let t=setInterval(()=>setSecsRaw(s=>s+1),1000);return()=>clearInterval(t)},[running]);useEffect(()=>{if(!paused)return;let t=setInterval(()=>activeHalf==="前半"?setLossFirst(s=>s+1):setLossSecond(s=>s+1),1000);return()=>clearInterval(t)},[paused,activeHalf]); useEffect(()=>setSecsRaw(0),[mins]);useEffect(()=>{try{let saved=localStorage.getItem("fieldsync_pending_result");if(saved)setPendingResult(JSON.parse(saved))}catch{}},[]);
 const win=(x:Game)=>x.sa!==x.sb?(x.sa>x.sb?x.a:x.b):(x.pa||0)!==(x.pb||0)?((x.pa||0)>(x.pb||0)?x.a:x.b):null; const lose=(x:Game)=>win(x)===x.a?x.b:win(x)===x.b?x.a:null;
 const nav=(t:Tab)=>{if((t==="score"||t==="settings"||t==="system")&&!admin)setLogin(true);else setTab(t)};
 const unlock=(v:string)=>{setPin(v);if(v===adminPassword){setTimeout(()=>{setAdmin(true);setLogin(false);setPin("");setTab("settings")},160)}};
 const commitResult=(result:Game)=>{let w=win(result),l=lose(result);if(!w)return;setGames(xs=>xs.map(x=>{if(x.id===result.id)return{...result,done:true};if(result.id==="m3"&&x.id==="m6")return{...x,a:w};if(result.id==="m4"&&x.id==="m6")return{...x,b:w};if(result.id==="m3"&&x.id==="c2")return{...x,a:l};if(result.id==="m4"&&x.id==="c2")return{...x,b:l};if(result.id==="m5"&&x.id==="m7")return{...x,a:w};if(result.id==="m6"&&x.id==="m7")return{...x,b:w};if(result.id==="c1"&&x.id==="c3")return{...x,a:w};if(result.id==="c2"&&x.id==="c3")return{...x,b:w};return x}));setPhase("試合終了");setRunning(false)};
 const notify=(message:string)=>{setToastMessage(message);setToast(true);setTimeout(()=>setToast(false),3000)};
 const send=()=>{let result={...g,done:true};if(!win(result))return;setConfirm(false);if(typeof navigator!=="undefined"&&!navigator.onLine){try{localStorage.setItem("fieldsync_pending_result",JSON.stringify(result))}catch{}setPendingResult(result);setRunning(false);notify("通信エラー・結果を端末に保存しました");return}commitResult(result);notify("結果を送信しました")};
 const retryPending=()=>{if(!pendingResult)return;if(typeof navigator!=="undefined"&&!navigator.onLine){notify("まだオフラインです。通信状況をご確認ください");return}commitResult(pendingResult);try{localStorage.removeItem("fieldsync_pending_result")}catch{}setPendingResult(null);notify("未送信の結果を送信しました")};
 const resetClock=()=>{setSecsRaw(0);setRunning(false);setPaused(false);setActiveHalf("前半");setLossFirst(0);setLossSecond(0);setPhase("試合前")};
 const startClock=()=>{let half:typeof activeHalf=phase==="ハーフタイム"?"後半":activeHalf;if(phase==="ハーフタイム"){setActiveHalf("後半");setSecsRaw(0)}setPaused(false);setRunning(true);setPhase(half)};
 const stopClock=()=>{if(!running)return;setRunning(false);setPaused(true);setPhase(`${activeHalf}・中断中`)};
 const endPeriod=()=>{setRunning(false);setPaused(false);setPhase(activeHalf==="前半"?"ハーフタイム":"試合終了")};
 const adjustLoss=(n:number)=>activeHalf==="前半"?setLossFirst(v=>Math.max(0,v+n)):setLossSecond(v=>Math.max(0,v+n));
 const rebuildBracket=(xs:Game[])=>{let map=new Map(xs.map(x=>[x.id,{...x}]));const w=(id:string)=>{let x=map.get(id);return x?.done?win(x):null},l=(id:string)=>{let x=map.get(id);return x?.done?lose(x):null};const assign=(id:string,a:string|null,b:string|null)=>{let x=map.get(id)!;if(x.a!==a||x.b!==b)map.set(id,{...x,a,b,sa:0,sb:0,pa:undefined,pb:undefined,done:false,ya:0,yb:0,ra:0,rb:0})};assign("m5",w("m1"),w("m2"));assign("m6",w("m3"),w("m4"));assign("c1",l("m1"),l("m2"));assign("c2",l("m3"),l("m4"));assign("m7",w("m5"),w("m6"));assign("c3",w("c1"),w("c2"));return xs.map(x=>map.get(x.id)!)};
 const saveRecovery=()=>{if(!recovery||!win(recovery))return;setGames(xs=>rebuildBracket(xs.map(x=>x.id===recovery.id?{...recovery,done:true}:x)));setRecovery(null);setToastMessage("修正結果を反映しました");setToast(true);setTimeout(()=>setToast(false),3000)};
 const notice=`【${info.name} 大会案内】\n\n■日時\n${info.date} ${info.time}\n\n■会場\n${info.venue}\n${info.address}\n${info.map}\n\n■対象・参加費\n${info.target}\n${info.fee}\n\n■当日の流れ\n${info.flow}\n\n■駐車場\n${info.parking}\n\n■雨天時\n${info.rain}\n\n■持ち物・注意事項\n${info.notes}\n\n■医事\n${info.medical}\n\n安全な大会運営へのご協力をお願いいたします。`;
 const copyNotice=async()=>{await navigator.clipboard.writeText(notice);setCopied(true);setTimeout(()=>setCopied(false),2200)};
 const downloadNotice=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([notice],{type:"text/plain;charset=utf-8"}));a.download=`${info.name}-保護者向け案内.txt`;a.click();URL.revokeObjectURL(a.href)};
 const printGuide=()=>{setTab("guide");setEditing(false);setTimeout(()=>window.print(),180)};
 const createTournament=()=>{setInfo({...initialInfo,name:"新しい大会",date:"",time:"",venue:"",address:"",map:"",host:"",fee:"",target:"",parking:"",rain:"",medical:"",notes:"",awards:"",flow:""});setPublished(false);setEditing(true);setTab("settings")};
 const navs:[Tab,string,any][]=[["bracket","トーナメント",Trophy],["schedule","対戦スケジュール",CalendarDays],["guide","大会案内",FileText],["score","審判スコア入力",Flag],["settings","大会設定",Settings],["system","システム設定",KeyRound]];
 return <main><header><button className="brand" onClick={()=>setTab("bracket")}><b>FIELD<span>SYNC</span></b><small>TOURNAMENT LIVE</small></button><nav>{navs.map(([t,l,I])=><button className={tab===t?"active":""} onClick={()=>nav(t)} key={t}><I/>{l}{!admin&&(t==="score"||t==="settings"||t==="system")&&<LockKeyhole/>}</button>)}</nav>{admin?<button className="admin" onClick={()=>{setAdmin(false);setTab("bracket")}}><ShieldCheck/>管理者モード<LogOut/></button>:<button className="admin" onClick={()=>setLogin(true)}><ShieldCheck/>管理者ログイン</button>}</header><div className="live"><i/>大会開催中 <b>U-12 グリーンフィールドカップ 2026</b><span>8月27日（木）</span></div>
 <div className="shell">
 {tab==="bracket"&&<><Title en="TOURNAMENT BRACKET" title="トーナメント表" sub="試合結果はリアルタイムで自動更新されます"/><div className="switch"><button className={stage==="main"?"on":""} onClick={()=>setStage("main")}><Trophy/>本戦トーナメント</button><button className={stage==="challenge"?"on":""} onClick={()=>setStage("challenge")}>チャレンジカップ</button></div><section className="bracket"><div className="sectionHead"><Trophy/><span><b>{stage==="main"?"本戦トーナメント":"チャレンジカップ"}</b><small>{stage==="main"?"優勝を目指すメイントーナメント":"1回戦敗退チームによる裏トーナメント"}</small></span></div><div className={`rounds ${stage}`}>{(stage==="main"?["1回戦","準決勝","決勝"]:["1回戦","決勝"]).map(r=><div className="round" key={r}><h3>{r}</h3><div>{games.filter(x=>x.stage===stage&&x.round===r).map(x=><Card g={x} key={x.id}/>)}</div></div>)}</div><aside>● <b>自動連携中</b>　1回戦の勝者は本戦へ、敗者はチャレンジカップへ自動で進みます。</aside></section></>}
 {tab==="schedule"&&<><Title en="MATCH SCHEDULE" title="対戦スケジュール" sub="コート別の試合予定と最新結果"/><div className="filters">{["すべて","Aコート","Bコート","Cコート"].map(c=><button className={court===c?"on":""} onClick={()=>setCourt(c)} key={c}>{c}</button>)}</div>{admin&&<div className="recoveryGuide"><RotateCcw/><span><b>結果リカバリー</b><small>終了した試合の「結果を修正」から訂正できます</small></span></div>}<section className="list">{games.filter(x=>court==="すべて"||x.court===court).map(x=><article key={x.id}><time>{x.time}<small>{x.no}</small></time><label>{x.court}</label><div><Team name={x.a}/><i>VS</i><Team name={x.b}/></div><strong>{x.done?`${x.sa} - ${x.sb}`:"–"}<small>{x.done?"✓ 終了":"予定"}</small>{admin&&x.done&&<button className="recoveryBtn" onClick={()=>setRecovery({...x})}><RotateCcw/>結果を修正</button>}</strong></article>)}</section></>}
 {tab==="system"&&admin&&<SystemSettings password={adminPassword} setPassword={setAdminPassword}/>}
 {tab==="settings"&&admin&&<div className="workflow"><span className="done"><i>1</i>大会作成</span><b/><span className={editing?"current":"done"}><i>2</i>概要設定</span><b/><span className={!editing&&!published?"current":published?"done":""}><i>3</i>確認・配信</span><b/><span className={published?"current":""}><i>4</i>公開完了</span></div>}
 {tab==="settings"&&admin&&!editing&&<SimpleAdminFlow info={info} mins={mins} setMins={setMins} pkRule={pkRule} setPkRule={setPkRule} format={format} setFormat={setFormat} published={published} editOverview={()=>setEditing(true)} createTournament={createTournament} preview={()=>setTab("guide")} printGuide={printGuide} publish={()=>setPublishConfirm(true)}/>}
 {tab==="settings"&&admin&&!editing&&<RuleNumberEditor mins={mins} setMins={setMins} pkRule={pkRule} setPkRule={setPkRule}/>}
 {tab==="settings"&&admin&&editing&&<AdminOverviewEditor info={info} setInfo={setInfo} finish={()=>setEditing(false)}/>}
 {tab==="guide"&&<><div className="guideTitle"><Title en="TOURNAMENT INFORMATION" title="大会案内" sub="保護者・参加チーム向けの大会情報"/>{admin&&<button className="editInfo" onClick={()=>setEditing(!editing)}><Settings/>{editing?"プレビューを見る":"大会概要を編集"}</button>}</div>{editing&&admin?<section className="infoEditor"><div className="editorHead"><span><Settings/><b>大会概要の設定</b><small>入力内容から保護者向け案内を自動生成します</small></span><button onClick={()=>setEditing(false)}><Check/>設定を反映</button></div><div className="formGrid">{([{k:"name",l:"大会名"},{k:"date",l:"開催日"},{k:"time",l:"開催時間"},{k:"venue",l:"会場名"},{k:"address",l:"住所"},{k:"map",l:"Google Maps URL"},{k:"host",l:"主催"},{k:"fee",l:"参加費"},{k:"target",l:"対象カテゴリー"}] as {k:keyof Info,l:string}[]).map(f=><label key={f.k}><span>{f.l}</span><input value={info[f.k]} onChange={e=>setInfo({...info,[f.k]:e.target.value})}/></label>)}{([{k:"flow",l:"当日の流れ"},{k:"parking",l:"駐車場・送迎"},{k:"rain",l:"雨天時の対応"},{k:"notes",l:"持ち物・注意事項"},{k:"medical",l:"医事・保険"},{k:"awards",l:"表彰"}] as {k:keyof Info,l:string}[]).map(f=><label className="full" key={f.k}><span>{f.l}</span><textarea rows={4} value={info[f.k]} onChange={e=>setInfo({...info,[f.k]:e.target.value})}/></label>)}</div></section>:<section className="guideLayout"><article className="guidePaper"><div className="guideHero"><small>保護者・参加チームの皆さまへ</small><h2>{info.name}</h2><p>大会当日のご案内</p></div><div className="keyFacts"><span><CalendarDays/><small>開催日</small><b>{info.date}</b><em>{info.time}</em></span><span><MapPin/><small>会場</small><b>{info.venue}</b><em>{info.address}</em></span></div><GuideBlock title="大会概要"><p><b>主催</b>{info.host}</p><p><b>対象</b>{info.target}</p><p><b>参加費</b>{info.fee}</p></GuideBlock><GuideBlock title="当日の流れ"><pre>{info.flow}</pre></GuideBlock><GuideBlock title="会場・駐車場"><p>{info.parking}</p><a href={info.map} target="_blank" rel="noreferrer"><MapPin/>Google Mapsで会場を見る</a></GuideBlock><GuideBlock title="雨天・医事対応"><p><b>雨天</b>{info.rain}</p><p><b>医事</b>{info.medical}</p></GuideBlock><GuideBlock title="持ち物・注意事項"><ul>{info.notes.split("\n").map((n,i)=><li key={i}>{n}</li>)}</ul></GuideBlock><GuideBlock title="表彰"><p>{info.awards}</p></GuideBlock><footer>安全で楽しい大会運営へのご協力をお願いいたします。<small>{info.name} 大会本部</small></footer></article><aside className="sharePanel"><span className="shareIcon"><FileText/></span><h3>保護者向け案内を自動生成</h3><p>設定した大会概要を、LINEやメールですぐ送れる文章に整形します。</p><div className="messagePreview"><small>送信プレビュー</small><pre>{notice}</pre></div><button className="copyBtn" onClick={copyNotice}>{copied?<Check/>:<Copy/>}{copied?"コピーしました":"案内文をコピー"}</button><button className="downloadBtn" onClick={downloadNotice}><Download/>テキストで保存</button>{!admin&&<small className="adminHint"><LockKeyhole/>編集は管理者ログイン後に行えます</small>}</aside></section>}</>}
 {tab==="score"&&admin&&<><Title en="REFEREE CONSOLE" title="審判スコア入力" sub="すべての操作はタップだけで完了します"/>{pendingResult&&<PendingResult game={pendingResult} retry={retryPending}/>}<div className="scoreLayout"><aside className="picker"><h3><CalendarDays/>担当試合を選択</h3>{games.filter(x=>x.a&&x.b&&!x.done).map(x=><button className={id===x.id?"on":""} onClick={()=>{setId(x.id);setPk(false);resetClock()}} key={x.id}><b>{x.time}</b><span>{x.a}<small>vs {x.b} · {x.court}</small></span></button>)}</aside><section className="console"><div className="consoleHead"><span>{g.no} · {g.court}<b>{g.time} キックオフ</b></span><em>{g.round}</em></div><div className="timer"><small>● {phase}</small><strong>{String(Math.floor(secs/60)).padStart(2,"0")}:{String(secs%60).padStart(2,"0")}</strong><p>{mins}分ハーフ · ストップウォッチ</p><div><button className="green" onClick={startClock}><Play/> {phase==="ハーフタイム"?"後半開始":paused?"再開":"前半開始"}</button><button onClick={stopClock} disabled={!running}><Square/>ストップ</button><button className="danger" onClick={endPeriod}><Flag/>{activeHalf==="前半"?"前半終了":"試合終了"}</button></div><div className={paused?"lossTime counting":"lossTime"}><span><Clock3/><small>ロスタイム目安</small><b>{activeHalf} ＋{Math.ceil((activeHalf==="前半"?lossFirst:lossSecond)/60)}分</b><em>{String(Math.floor((activeHalf==="前半"?lossFirst:lossSecond)/60)).padStart(2,"0")}:{String((activeHalf==="前半"?lossFirst:lossSecond)%60).padStart(2,"0")}</em></span><div><button onClick={()=>adjustLoss(-30)}><Minus/>30秒</button><small>{paused?"● 中断時間を自動計測中":"ストップ中の時間を自動加算"}</small><button onClick={()=>adjustLoss(30)}><Plus/>30秒</button></div><footer>前半 ＋{Math.ceil(lossFirst/60)}分　／　後半 ＋{Math.ceil(lossSecond/60)}分</footer></div></div><div className="boards">{(["a","b"] as const).map((s,i)=><div className="board" key={s}><Mark name={g[s]}/><small>TEAM {s.toUpperCase()}</small><h2>{g[s]}</h2><div className="counter"><button onClick={()=>add(i?"sb":"sa",-1)}><Minus/></button><b>{i?g.sb:g.sa}</b><button className="green" onClick={()=>add(i?"sb":"sa",1)}><Plus/></button></div><div className="cards"><button onClick={()=>add(i?"yb":"ya",1)}>🟨 イエロー <b>{i?g.yb:g.ya}</b></button><button onClick={()=>add(i?"rb":"ra",1)}>🟥 レッド <b>{i?g.rb:g.ra}</b></button></div></div>)}</div><div className="pkToggle"><span><b>PK戦モード</b><small>同点の場合のみ使用</small></span><button className={pk?"on":""} onClick={()=>setPk(!pk)}><i/></button></div>{pk&&<div className="pkbox">{(["a","b"] as const).map((s,i)=><div key={s}><Team name={g[s]}/><span><button onClick={()=>add(i?"pb":"pa",-1)}><Minus/></button><b>{i?(g.pb||0):(g.pa||0)}</b><button onClick={()=>add(i?"pb":"pa",1)}><Plus/></button></span></div>)}</div>}<button className="submit" disabled={!win(g)} onClick={()=>setConfirm(true)}><Flag/><span>本部に結果を送信<small>スコアを確定して全画面に反映</small></span></button></section></div></>}
 {tab==="settings"&&admin&&!editing&&<div className="deliveryBar"><span><b>{published?"大会案内は公開中です":"大会概要の確認ができました"}</b><small>PDF作成または保護者への公開・配信へ進めます</small></span><button onClick={()=>setEditing(true)}><Settings/>概要を編集</button><button onClick={printGuide}><Printer/>PDFを作成</button><button className="deliver" onClick={()=>setPublishConfirm(true)}>{published?<Check/>:<Send/>}{published?"公開中・再配信":"公開・配信"}</button></div>}
 {tab==="settings"&&admin&&<><Title en="TOURNAMENT ADMIN" title="大会作成・管理" sub="大会の作成から公開までを一つの流れで管理"/><section className="tournamentManager"><div><span className={published?"status liveStatus":"status"}>{published?"公開中":"下書き"}</span><h2>{info.name}</h2><p>{info.date||"開催日未設定"} · {info.venue||"会場未設定"}</p></div><div><button onClick={()=>{setTab("guide");setEditing(true)}}><Settings/>概要を編集</button><button className="newTournament" onClick={createTournament}><PlusCircle/>新しい大会を作成</button></div></section><h3 className="subheading">競技レギュレーション</h3><div className="settings"><Setting icon={<Clock3/>} title="試合時間" sub="各試合の基本時間を選択"><div className="choices">{[15,20,30].map(n=><button className={mins===n?"on":""} onClick={()=>setMins(n)} key={n}><b>{n}</b>分</button>)}</div></Setting><Setting icon={<Settings/>} title="試合形式" sub="前後半制または1本勝負"><div className="wide">{[["half","前後半制"],["single","1本勝負"]].map(x=><button className={format===x[0]?"on":""} onClick={()=>setFormat(x[0])} key={x[0]}>{x[1]}{format===x[0]&&<Check/>}</button>)}</div></Setting><Setting icon={<Trophy/>} title="PK戦ルール" sub="規定人数終了後はサドンデス"><div className="choices">{[1,3,5].map(n=><button className={pkRule===n?"on":""} onClick={()=>setPkRule(n)} key={n}><b>{n}</b>人制</button>)}</div></Setting></div><div className="saved"><Check/>設定は自動保存され、審判画面に即時反映されます</div></>}
 </div><nav className="mobile">{navs.map(([t,l,I])=><button className={tab===t?"active":""} onClick={()=>nav(t)} key={t}><I/>{l.replace("対戦スケジュール","日程").replace("審判スコア入力","スコア")}</button>)}</nav>
 {login&&<div className="overlay" onClick={()=>setLogin(false)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setLogin(false)}><X/></button><ShieldCheck className="heroIcon"/><small>STAFF ONLY</small><h2>管理者・審判ログイン</h2><p>4桁のパスコードを入力してください</p><div className="dots">{[0,1,2,3].map(n=><i className={pin.length>n?"on":""} key={n}/>)}</div><div className="keypad">{[1,2,3,4,5,6,7,8,9,0].map(n=><button onClick={()=>pin.length<4&&unlock(pin+n)} key={n}>{n}</button>)}<button onClick={()=>setPin(pin.slice(0,-1))}>⌫</button></div><em>デモ用パスコード: 1234</em></div></div>}
 {confirm&&<div className="overlay"><div className="modal"><Flag className="heroIcon"/><h2>試合結果を送信しますか？</h2><div className="final"><span><Team name={g.a}/><b>{g.sa}</b></span><i>対</i><span><Team name={g.b}/><b>{g.sb}</b></span></div>{pk&&<p>PK {g.pa||0} - {g.pb||0}</p>}<div className="actions"><button onClick={()=>setConfirm(false)}>戻って確認</button><button className="green" onClick={send}>この内容で送信</button></div></div></div>}{recovery&&<RecoveryModal game={recovery} setGame={setRecovery} close={()=>setRecovery(null)} save={saveRecovery} winner={win(recovery)}/>} {publishConfirm&&<div className="overlay"><div className="modal publishModal"><Send className="heroIcon"/><small>FINAL STEP</small><h2>大会案内を公開・配信しますか？</h2><p>保護者向け大会案内が閲覧可能になります。<br/>案内文はLINEやメールにもコピーできます。</p><div className="publishSummary"><b>{info.name}</b><span>{info.date} · {info.venue}</span></div><div className="actions"><button onClick={()=>setPublishConfirm(false)}>戻って確認</button><button className="green" onClick={()=>{setPublished(true);setPublishConfirm(false);setToastMessage("大会案内を公開しました");setToast(true);setTimeout(()=>setToast(false),3000)}}><Send/>公開・配信する</button></div></div></div>}{toast&&<div className="toast"><Check/><span><b>{toastMessage}</b><small>保護者向けページに反映済みです</small></span></div>}</main>
}
function Title({en,title,sub}:{en:string,title:string,sub:string}){return <div className="title"><span><small>{en}</small><h1>{title}</h1><p>{sub}</p></span><b>● LIVE <em>自動更新中</em></b></div>}
function Setting({icon,title,sub,children}:{icon:any,title:string,sub:string,children:any}){return <section className="setting"><i>{icon}</i><h2>{title}</h2><p>{sub}</p>{children}</section>}
function GuideBlock({title,children}:{title:string,children:any}){return <section className="guideBlock"><h3>{title}</h3>{children}</section>}
function AdminOverviewEditor({info,setInfo,finish}:{info:Info,setInfo:(v:Info)=>void,finish:()=>void}){
 const [step,setStep]=useState(1);const groups:{title:string,sub:string,fields:[keyof Info,string,boolean?][]}[]=[
  {title:"基本情報",sub:"まずは大会名・日時・会場だけ",fields:[["name","大会名"],["date","開催日"],["time","開催時間"],["venue","会場名"],["address","住所"],["map","Google Maps URL"]]},
  {title:"参加条件",sub:"主催・参加費・対象カテゴリー",fields:[["host","主催"],["fee","参加費"],["target","対象カテゴリー"]]},
  {title:"保護者向け案内",sub:"当日の注意事項をまとめて設定",fields:[["flow","当日の流れ",true],["parking","駐車場・送迎",true],["rain","雨天時の対応",true],["notes","持ち物・注意事項",true],["medical","医事・保険",true],["awards","表彰",true]]}
 ];const group=groups[step-1];const next=()=>step<3?setStep(step+1):finish();
 const mapUrl=(venue:string,address:string)=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${venue} ${address}`.trim())}`;
 const update=(k:keyof Info,value:string)=>setInfo({...info,[k]:value,...((k==="venue"||k==="address")?{map:mapUrl(k==="venue"?value:info.venue,k==="address"?value:info.address)}:{})});
 const dateValue=(()=>{let m=info.date.match(/(\d{4})年(\d{1,2})月(\d{1,2})日/);return m?`${m[1]}-${m[2].padStart(2,"0")}-${m[3].padStart(2,"0")}`:/^\d{4}-\d{2}-\d{2}$/.test(info.date)?info.date:""})();
 const setDate=(value:string)=>{let d=new Date(`${value}T00:00:00`),days="日月火水木金土";update("date",`${d.getFullYear()}年${d.getMonth()+1}月${d.getDate()}日（${days[d.getDay()]}）`)};
 const [start="9:00",end="17:15"]=info.time.split("〜"),times=Array.from({length:65},(_,i)=>{let total=360+i*15;return `${Math.floor(total/60)}:${String(total%60).padStart(2,"0")}`});
 const categories=["U-6","U-7","U-8","U-9","U-10","U-11","U-12","U-10〜U-12（混合チーム可）","U-13〜U-15","U-16〜U-18","一般・社会人"];
 const renderField=(k:keyof Info,l:string,long?:boolean)=>{if(k==="date")return <label key={k}><span>{l}</span><div className="calendarInput"><CalendarDays/><input type="date" value={dateValue} onChange={e=>setDate(e.target.value)}/></div><small className="fieldHelp">カレンダーから開催日を選択</small></label>;if(k==="time")return <label key={k}><span>{l}</span><div className="timeSelect"><select value={start} onChange={e=>update("time",`${e.target.value}〜${end}`)}>{times.map(t=><option key={t}>{t}</option>)}</select><b>〜</b><select value={end} onChange={e=>update("time",`${start}〜${e.target.value}`)}>{times.map(t=><option key={t}>{t}</option>)}</select></div><small className="fieldHelp">開始時間と終了時間を選択</small></label>;if(k==="target")return <label key={k}><span>{l}</span><select value={categories.includes(info.target)?info.target:""} onChange={e=>update("target",e.target.value)}><option value="" disabled>カテゴリーを選択</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label>;if(k==="map")return <div className="autoMap full" key={k}><div><MapPin/><span><b>マップ自動反映</b><small>{info.venue||"会場名"}・{info.address||"住所"}から地図を表示します</small></span><a href={info.map} target="_blank" rel="noreferrer">大きな地図で確認</a></div>{(info.venue||info.address)&&<iframe title="会場マップ" loading="lazy" src={`https://www.google.com/maps?q=${encodeURIComponent(`${info.venue} ${info.address}`)}&output=embed`}/>}</div>;return <label className={long?"full":""} key={k}><span>{l}</span>{long?<textarea rows={k==="notes"||k==="flow"?5:3} value={info[k]} onChange={e=>update(k,e.target.value)}/>:<input value={info[k]} onChange={e=>update(k,e.target.value)}/>}</label>};
 return <section className="infoEditor lockedEditor easyOverview"><div className="editorHead"><span><LockKeyhole/><b>かんたん大会概要設定</b><small>3ステップで案内とPDFを自動作成します</small></span><button onClick={next}>{step===3?<Check/>:<span>{step+1}</span>}{step===3?"設定して確認へ":"次へ進む"}</button></div><div className="overviewStepper">{groups.map((g,i)=><button key={g.title} className={step===i+1?"current":step>i+1?"complete":""} onClick={()=>setStep(i+1)}><i>{step>i+1?<Check/>:i+1}</i><span><b>{g.title}</b><small>{g.sub}</small></span></button>)}</div>{step===1&&<div className="copyPrevious"><span><Copy/><b>前回とほぼ同じ大会ですか？</b><small>Bond Cupの内容をコピーして、変更点だけ直せます</small></span><button onClick={()=>setInfo({...initialInfo})}><Copy/>前回のBond Cupをコピー</button></div>}<div className="stepIntro"><small>STEP {step} / 3</small><h2>{group.title}</h2><p>{group.sub}</p></div><div className="formGrid easyForm">{group.fields.map(([k,l,long])=>renderField(k,l,long))}</div><div className="overviewFooter">{step>1?<button onClick={()=>setStep(step-1)}>前へ戻る</button>:<span/>}<p>入力内容はこの画面内で自動保存されます</p><button className="nextStep" onClick={next}>{step===3?<><Check/>設定して確認へ</>:<>次へ進む <b>→</b></>}</button></div></section>}
function RuleNumberEditor({mins,setMins,pkRule,setPkRule}:{mins:number,setMins:Dispatch<SetStateAction<number>>,pkRule:number,setPkRule:Dispatch<SetStateAction<number>>}){const change=(set:Dispatch<SetStateAction<number>>,value:string,min:number,max:number)=>set(Math.min(max,Math.max(min,Number(value)||min)));return <section className="customRuleEditor"><div className="customRuleHead"><span><Settings/><b>数値を直接変更</b><small>クイック選択にない数値も自由に設定できます</small></span><em><LockKeyhole/>管理者のみ</em></div><div className="customNumberGrid"><label><span>基本試合時間</span><div><button onClick={()=>setMins(v=>Math.max(1,v-1))}><Minus/></button><input type="number" min="1" max="120" inputMode="numeric" value={mins} onChange={e=>change(setMins,e.target.value,1,120)}/><b>分</b><button onClick={()=>setMins(v=>Math.min(120,v+1))}><Plus/></button></div><small>前後半制の場合は1ハーフの時間</small></label><label><span>PK戦の規定人数</span><div><button onClick={()=>setPkRule(v=>Math.max(1,v-1))}><Minus/></button><input type="number" min="1" max="20" inputMode="numeric" value={pkRule} onChange={e=>change(setPkRule,e.target.value,1,20)}/><b>人</b><button onClick={()=>setPkRule(v=>Math.min(20,v+1))}><Plus/></button></div><small>規定人数終了後にサドンデス</small></label></div></section>}
function SimpleAdminFlow({info,mins,setMins,pkRule,setPkRule,format,setFormat,published,editOverview,createTournament,preview,printGuide,publish}:{info:Info,mins:number,setMins:Dispatch<SetStateAction<number>>,pkRule:number,setPkRule:Dispatch<SetStateAction<number>>,format:string,setFormat:Dispatch<SetStateAction<string>>,published:boolean,editOverview:()=>void,createTournament:()=>void,preview:()=>void,printGuide:()=>void,publish:()=>void}){return <section className="simpleAdmin"><div className="simpleHero"><span><LockKeyhole/><small>ADMIN ONLY</small><h1>かんたん大会作成</h1><p>上から順番に3つ設定するだけで公開できます</p></span><button onClick={createTournament}><PlusCircle/>新しい大会</button></div><div className="simpleSteps"><article><header><i>1</i><span><b>大会概要</b><small>日時・会場・注意事項</small></span><em className={info.date&&info.venue?"complete":""}>{info.date&&info.venue?"設定済み":"未設定"}</em></header><div className="overviewSummary"><b>{info.name}</b><p>{info.date||"開催日を入力してください"}</p><p>{info.venue||"会場を入力してください"}</p></div><button className="stepAction" onClick={editOverview}><Settings/>大会概要を入力・編集</button></article><article><header><i>2</i><span><b>試合ルール</b><small>時間・形式・PK人数</small></span><em className="complete">設定済み</em></header><RuleNumberEditor mins={mins} setMins={setMins} pkRule={pkRule} setPkRule={setPkRule}/><div className="simpleFormat"><span>試合形式</span><button className={format==="half"?"selected":""} onClick={()=>setFormat("half")}>前後半制</button><button className={format==="single"?"selected":""} onClick={()=>setFormat("single")}>1本勝負</button></div></article><article><header><i>3</i><span><b>確認して配信</b><small>プレビュー・PDF・公開</small></span><em className={published?"complete":""}>{published?"公開中":"未公開"}</em></header><div className="finalCheck"><b>{info.name}</b><span>{mins}分 · {format==="half"?"前後半制":"1本勝負"} · PK {pkRule}人制</span></div><div className="simpleActions"><button onClick={preview}><FileText/>案内を確認</button><button onClick={printGuide}><Printer/>PDF作成</button><button className="publishNow" onClick={publish}><Send/>{published?"再配信する":"公開・配信する"}</button></div></article></div></section>}

function PendingResult({game,retry}:{game:Game,retry:()=>void}){return <section className="pendingResult"><i><CloudOff/></i><span><small>端末内に安全に保存済み</small><b>未送信の試合結果があります</b><p>{game.no}　{game.a} <strong>{game.sa} - {game.sb}</strong> {game.b}{game.pa!==undefined&&`（PK ${game.pa} - ${game.pb}）`}</p></span><button onClick={retry}><RefreshCw/>通信を確認して再試行</button></section>}

function RecoveryModal({game,setGame,close,save,winner}:{game:Game,setGame:Dispatch<SetStateAction<Game|null>>,close:()=>void,save:()=>void,winner:string|null}){
 const change=(key:"sa"|"sb"|"pa"|"pb",n:number)=>setGame({...game,[key]:Math.max(0,Number(game[key]||0)+n)});
 const tied=game.sa===game.sb;
 return <div className="overlay"><div className="modal recoveryModal"><button className="close" onClick={close}><X/></button><RotateCcw className="heroIcon"/><small>RESULT RECOVERY</small><h2>試合結果を修正</h2><p>{game.no} · {game.court}　送信済みの結果を訂正します</p><div className="recoveryScores">{(["a","b"] as const).map((side,i)=><div key={side}><Team name={game[side]}/><span><button onClick={()=>change(i?"sb":"sa",-1)}><Minus/></button><b>{i?game.sb:game.sa}</b><button onClick={()=>change(i?"sb":"sa",1)}><Plus/></button></span></div>)}</div>{tied&&<div className="recoveryPk"><b>PK結果</b>{(["a","b"] as const).map((side,i)=><div key={side}><Team name={game[side]}/><span><button onClick={()=>change(i?"pb":"pa",-1)}><Minus/></button><b>{i?(game.pb||0):(game.pa||0)}</b><button onClick={()=>change(i?"pb":"pa",1)}><Plus/></button></span></div>)}</div>}<div className="recoveryWarning"><AlertTriangle/><span><b>勝者が変わる場合</b><small>進出先を再計算し、影響する後続試合の結果を未確定へ戻します。</small></span></div><div className="recoveryWinner">修正後の勝者 <b>{winner||"未確定"}</b></div><div className="actions"><button onClick={close}>キャンセル</button><button className="green" disabled={!winner} onClick={save}><Check/>修正を確定</button></div></div></div>;
}

function SystemSettings({password,setPassword}:{password:string,setPassword:Dispatch<SetStateAction<string>>}){
 const [current,setCurrent]=useState(""),[next,setNext]=useState(""),[again,setAgain]=useState(""),[message,setMessage]=useState(""),[confirmResult,setConfirmResult]=useState(true),[sound,setSound]=useState(true),[vibration,setVibration]=useState(true),[liveNotice,setLiveNotice]=useState(true);
 const numeric=(value:string,setter:Dispatch<SetStateAction<string>>)=>setter(value.replace(/\D/g,"").slice(0,4));
 const changePassword=()=>{if(current!==password)return setMessage("現在のパスワードが違います");if(next.length!==4)return setMessage("新しいパスワードは数字4桁で入力してください");if(next!==again)return setMessage("確認用パスワードが一致しません");setPassword(next);setCurrent("");setNext("");setAgain("");setMessage("パスワードを変更しました")};
 const Toggle=({on,set}:{on:boolean,set:Dispatch<SetStateAction<boolean>>})=><button type="button" className={on?"systemToggle on":"systemToggle"} onClick={()=>set(v=>!v)} aria-label={on?"オン":"オフ"}><i/></button>;
 return <><Title en="SYSTEM SETTINGS" title="パスワード・システム設定" sub="管理者ログインと大会運営時の動作を設定"/><section className="systemGrid"><article className="passwordCard"><div className="systemCardHead"><i><KeyRound/></i><span><h2>管理者パスワード変更</h2><p>次回の管理者ログインから新しい番号を使用します</p></span></div><div className="passwordFields"><label><span>現在のパスワード</span><input type="password" inputMode="numeric" maxLength={4} value={current} onChange={e=>numeric(e.target.value,setCurrent)} placeholder="数字4桁"/></label><label><span>新しいパスワード</span><input type="password" inputMode="numeric" maxLength={4} value={next} onChange={e=>numeric(e.target.value,setNext)} placeholder="数字4桁"/></label><label><span>新しいパスワード（確認）</span><input type="password" inputMode="numeric" maxLength={4} value={again} onChange={e=>numeric(e.target.value,setAgain)} placeholder="もう一度入力"/></label></div>{message&&<p className={message.includes("変更しました")?"passwordMessage success":"passwordMessage"}>{message}</p>}<button className="passwordSave" onClick={changePassword}><Check/>パスワードを変更</button><small className="localNote"><LockKeyhole/>プロトタイプのため、この端末で画面を開いている間のみ保存されます</small></article><article className="operationCard"><div className="systemCardHead"><i><Settings/></i><span><h2>運用設定</h2><p>審判画面と結果配信の動作を選べます</p></span></div><div className="systemRows"><div><i><Bell/></i><span><b>結果送信前の確認</b><small>誤送信を防ぐ確認画面を表示</small></span><Toggle on={confirmResult} set={setConfirmResult}/></div><div><i><Volume2/></i><span><b>操作音</b><small>得点・カード入力時に音で知らせる</small></span><Toggle on={sound} set={setSound}/></div><div><i><Smartphone/></i><span><b>ボタン操作時の振動</b><small>屋外でも入力を手応えで確認</small></span><Toggle on={vibration} set={setVibration}/></div><div><i><Flag/></i><span><b>ライブ更新のお知らせ</b><small>結果反映時に完了通知を表示</small></span><Toggle on={liveNotice} set={setLiveNotice}/></div></div><div className="settingStatus"><ShieldCheck/><span><b>管理者専用エリア</b><small>この画面は管理者ログイン中だけ表示されます</small></span></div></article></section></>;
}
